### ISSUE TITLE
Failed to fetch GPG key

### ISSUE THREAD

**Issue by stevenscg** [threatstack/threatstack-ansible#36] opened 2017-11-12 21:47 UTC
Latest version of this role on an RHEL7/CentOS7 installation fails with this:

```
TASK [threatstack : Add ThreatStack repo GPG key.] *************************************************
fatal: [10.101.20.94]: FAILED! => {"changed": false, "failed": true, "msg": "failed to fetch key at https://app.threatstack.com/RPM-GPG-KEY-THREATSTACK , error was: HTTP Error 403: Forbidden"}
```

I can download the key file shown at the URL above, but obviously have to be logged into my account to do so.

#### Workaround

Download the key while logged in, add it to the role in a `files` directory, update the task to upload the file and then install it.

For yum-based systems:
```
- name: Upload ThreatStack repo GPG key
  copy:
    src: RPM-GPG-KEY-THREATSTACK
    dest: /etc/pki/rpm-gpg/

- name: Add ThreatStack repo GPG key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-THREATSTACK
```

**Comment by florianparain** [comment] 2017-11-13 12:19
I have the same issue with Ubuntu 16.04
```
{
  "changed": false,
  "failed": true,
  "msg": "Failed to download key at https://app.threatstack.com/APT-GPG-KEY-THREATSTACK: HTTP Error 403: Forbidden"
}
```

**Comment by florianparain** [comment] 2017-11-14 12:35
Answer from the Threat Stack support:

We're aware of this problem, and our team is actively investigating the cause of it. As we continue to learn more, I'll keep you posted.

**Comment by stevenscg** [comment] 2017-12-06 21:04
@florianparain Any updates on this?

**Comment by jbaublitz** [comment] 2017-12-07 20:10
@stevenscg I looked into it and the issue should be resolved. We have have tested it on our side and no longer are able to reproduce this. Are you still seeing the error?

**Comment by stevenscg** [comment] 2017-12-07 20:13
Thanks @jbaublitz. I have a workaround in my version of the role. I'll check it when I update the role next.

**Comment by jbaublitz** [comment] 2018-01-16 18:07
We've heard no further reports of this being an issue so I'm closing this one.

**Closed by jbaublitz** 2018-01-16 18:07 UTC
